### ISSUE TITLE
Unpublish from apm?

### ISSUE THREAD

**Issue by Arcanemagus** [kepler0/linter-clang-plus#1]
Looks like this is from before you took over https://github.com/AtomLinter/linter-clang, did you still want to keep this around?

**Comment by keplersj** [comment]
I've tried before and I wasn't able to.

You have my permission to unpublish if you would like to try however.

**Comment by Arcanemagus** [comment]
![image](https://cloud.githubusercontent.com/assets/427137/13085354/b14d8f3c-d492-11e5-99c1-e7c3ad045946.png)

I wonder if it's because the repo changed URLs?

**Comment by Arcanemagus** [comment]
![image](https://cloud.githubusercontent.com/assets/427137/13085623/f3fa4c3e-d493-11e5-807c-1ba69356ff5b.png)

Well that didn't work...

**Comment by Arcanemagus** [comment]
Next thing I can think of to try is asking in #packages on Slack :confused:.

**Comment by keplersj** [comment]
It's gone! https://atom.io/packages/linter-clang-plus returns a 404. Archiving this repo now.
